#!/usr/bin/env bash

# To prevent code from being accidentally committed, simply add a comment near your
# debug code containing the keyword NOCOMMIT_KEYWORD and this will abort the commit.

NOCOMMIT_KEYWORD="!nocommit"

if git commit -v --dry-run | grep $NOCOMMIT_KEYWORD >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the ${NOCOMMIT_KEYWORD} keyword if you want to commit."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  else
    exit 0
  fi
fi
